---
functional:
  - Пользователь должени иметь возможность создать игру
  - При создании игры должна быть возможность выбора сложности
  - При создании игры должна быть возможность выбора противника (бот или онлайн игрок)
  - При создании игры должна быть возможность выбора времени продолжительнсти игры
  - Пользователь может зайти в любую игру, активную в данный момент, в качестве зрителя
  - Пользователь может общаться в чате с другими пользователями

  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
  - На главной странице должен быть список всех пользователей, находящихся онлайн
implicit: #неявные
  - 
