---
functional:
  - Пользователь должени иметь возможность регистрации по e-mail
  - Пользователь должени иметь возможность создать игру
  - При создании игры должна быть возможность выбора сложности
  - При создании игры должна быть возможность выбора противника (бот или онлайн игрок)
  - При создании игры должна быть возможность выбора времени продолжительнсти игры
  - Пользователь может зайти в любую игру, активную в данный момент, в качестве зрителя
  - Пользователь может подключиться к игре, открытой другим пользователем (против игроков)
  - Пользователь может общаться в чате с другими пользователями
  - На главной странице должен быть список всех пользователей, находящихся онлайн
  - Оба игрока во время игры должны видеть два редактора (слева - свой редактор, справа - соперника)
  - Каждый игрок видит код своего соперника в режиме он-лайн
  - Каждый игрок имеет кнопку "check" для проверки своего решения. Попыток проверки не ограничено
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Кнопки "Fight" и "Show" на главной странице должны быть разных цветов
